#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
GitHub Repository Health Analyzer
GitHub仓库健康度分析器

A tool to analyze GitHub repository health metrics including stars, forks,
contributors, and community activity.
"""

import requests
import json
import os
import sys
from datetime import datetime, timedelta
from collections import Counter
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.dates import DateFormatter
import numpy as np
from urllib.parse import urlparse
import base64

# Translation dictionary
I18N = {
    'en': {
        'analyzing': '🔍 Analyzing {owner}/{repo}...',
        'data_fetched': '✅ Data fetched successfully!',
        'warning': '⚠️  Warning: {url} returned {status}',
        'error_fetch': '⚠️  Error fetching {url}: {error}',
        'chart_saved': '📊 Chart saved: {path}',
        'json_saved': '💾 JSON data saved: {path}',
        'analysis_complete': '\n✅ Analysis complete!',
        'repo_not_found': 'Repository not found or API rate limit exceeded',
        
        # Summary
        'repo_health_report': '📊 GitHub Repository Health Report',
        'repository': '📁 Repository',
        'description': '📝 Description',
        'stars': '⭐ Stars',
        'forks': '🍴 Forks',
        'watchers': '👁️ Watchers',
        'health_score': '🏥 Health Score',
        'detailed_breakdown': '📊 Detailed Breakdown',
        'generated': 'Generated',
        
        # Chart titles
        'repo_popularity': 'Repository Popularity',
        'top_contributors': 'Top 5 Contributors',
        'overall_health': 'Overall Health',
        'score': 'Score (0-100)',
        'pass_line': 'Pass Line',
        'issue_status': 'Issue Status (Avg Resolution: {days:.1f} days)',
        'open': 'Open',
        'closed': 'Closed',
        'pr_status': 'Pull Request Status (Merge Rate: {rate:.1f}%)',
        'merged': 'Merged',
        'recent_activity': 'Recent Commit Activity (90 days)',
        'date': 'Date',
        'commits': 'Commits',
        'contributions': 'Contributions',
        
        # HTML Report
        'overall_health_score': 'Overall Health Score',
        'grade': 'Grade',
        'factor': 'Factor',
        'bar': 'Bar',
        'basic_statistics': '📈 Basic Statistics',
        'primary_language': 'Primary Language',
        'license': 'License',
        'contributors': '👥 Contributors',
        'total_contributors': 'Total Contributors',
        'total_contributions': 'Total Contributions',
        'top_contributors_list': 'Top Contributors',
        'issues': '🐛 Issues',
        'open_issues': 'Open Issues',
        'closed_issues': 'Closed Issues',
        'resolution_rate': 'Resolution Rate',
        'avg_resolution_time': 'Avg Resolution Time',
        'pull_requests': '🔀 Pull Requests',
        'open_prs': 'Open PRs',
        'merged_prs': 'Merged PRs',
        'closed_prs': 'Closed PRs',
        'merge_rate': 'Merge Rate',
        'recent_commits': '💻 Recent Commits (90 days)',
        'total_commits': 'Total Commits',
        'unique_authors': 'Unique Authors',
        'health_factors': '🎯 Health Score Factors',
        'report_footer': 'Report generated by GitHub Repo Analyzer',
        
        # Grades
        'grade_A+': 'A+ 🌟',
        'grade_A': 'A',
        'grade_B+': 'B+',
        'grade_B': 'B',
        'grade_C': 'C',
        'grade_D': 'D',
        'grade_F': 'F',
        
        # Factors
        'stars_popularity': 'Stars Popularity',
        'contributor_diversity': 'Contributor Diversity',
        'issue_resolution': 'Issue Resolution',
        'pr_merge_rate': 'PR Merge Rate',
        'recent_activity_factor': 'Recent Activity',
        
        # Status
        'no_license': 'No license',
        'unknown': 'Unknown',
        'days': 'days',
    },
    'zh': {
        'analyzing': '🔍 正在分析 {owner}/{repo}...',
        'data_fetched': '✅ 数据获取成功！',
        'warning': '⚠️  警告: {url} 返回 {status}',
        'error_fetch': '⚠️  错误获取 {url}: {error}',
        'chart_saved': '📊 图表已保存: {path}',
        'json_saved': '💾 JSON 数据已保存: {path}',
        'analysis_complete': '\n✅ 分析完成！',
        'repo_not_found': '仓库不存在或 API 速率限制已达到',
        
        # Summary
        'repo_health_report': '📊 GitHub 仓库健康度报告',
        'repository': '📁 仓库',
        'description': '📝 描述',
        'stars': '⭐ Star 数',
        'forks': '🍴 Fork 数',
        'watchers': '👁️ 关注者',
        'health_score': '🏥 健康评分',
        'detailed_breakdown': '📊 详细得分',
        'generated': '生成时间',
        
        # Chart titles
        'repo_popularity': '仓库受欢迎度',
        'top_contributors': '前 5 位贡献者',
        'overall_health': '整体健康度',
        'score': '得分 (0-100)',
        'pass_line': '及格线',
        'issue_status': 'Issue 状态 (平均解决: {days:.1f} 天)',
        'open': '开启',
        'closed': '关闭',
        'pr_status': 'PR 状态 (合并率: {rate:.1f}%)',
        'merged': '已合并',
        'recent_activity': '最近提交活动 (90天)',
        'date': '日期',
        'commits': '提交数',
        'contributions': '贡献数',
        
        # HTML Report
        'overall_health_score': '整体健康评分',
        'grade': '等级',
        'factor': '指标',
        'bar': '进度',
        'basic_statistics': '📈 基础统计',
        'primary_language': '主要语言',
        'license': '许可证',
        'contributors': '👥 贡献者',
        'total_contributors': '贡献者总数',
        'total_contributions': '总贡献数',
        'top_contributors_list': '主要贡献者',
        'issues': '🐛 Issues',
        'open_issues': '开启的 Issues',
        'closed_issues': '关闭的 Issues',
        'resolution_rate': '解决率',
        'avg_resolution_time': '平均解决时间',
        'pull_requests': '🔀 Pull Requests',
        'open_prs': '开启的 PRs',
        'merged_prs': '已合并的 PRs',
        'closed_prs': '关闭的 PRs',
        'merge_rate': '合并率',
        'recent_commits': '💻 最近提交 (90天)',
        'total_commits': '总提交数',
        'unique_authors': '独立作者',
        'health_factors': '🎯 健康评分因素',
        'report_footer': '报告由 GitHub 仓库分析器生成',
        
        # Grades
        'grade_A+': 'A+ 🌟',
        'grade_A': 'A',
        'grade_B+': 'B+',
        'grade_B': 'B',
        'grade_C': 'C',
        'grade_D': 'D',
        'grade_F': 'F',
        
        # Factors
        'stars_popularity': 'Star 人气',
        'contributor_diversity': '贡献者多样性',
        'issue_resolution': 'Issue 解决率',
        'pr_merge_rate': 'PR 合并率',
        'recent_activity_factor': '近期活跃度',
        
        # Status
        'no_license': '无许可证',
        'unknown': '未知',
        'days': '天',
    }
}


class GitHubRepoAnalyzer:
    def __init__(self, repo_url, lang='en'):
        """Initialize with GitHub repository URL"""
        self.repo_url = repo_url
        self.owner, self.repo = self._parse_url(repo_url)
        self.base_api = f"https://api.github.com/repos/{self.owner}/{self.repo}"
        self.raw_base = f"https://raw.githubusercontent.com/{self.owner}/{self.repo}"
        self.data = {}
        self.lang = lang
        self.t = I18N[lang]
        
    def _parse_url(self, url):
        """Parse GitHub URL to extract owner and repo"""
        parsed = urlparse(url)
        path_parts = parsed.path.strip('/').split('/')
        if len(path_parts) >= 2:
            return path_parts[0], path_parts[1]
        raise ValueError("Invalid GitHub URL")
    
    def fetch_all_data(self):
        """Fetch all repository data from GitHub API"""
        print(self.t['analyzing'].format(owner=self.owner, repo=self.repo))
        
        # Basic repo info
        self.data['basic'] = self._fetch_json(self.base_api)
        
        # Contributors
        self.data['contributors'] = self._fetch_json(f"{self.base_api}/contributors?per_page=100")
        
        # Recent commits (for activity analysis)
        since = (datetime.now() - timedelta(days=90)).isoformat()
        self.data['commits'] = self._fetch_json(f"{self.base_api}/commits?since={since}&per_page=100")
        
        # Issues
        self.data['issues'] = self._fetch_json(f"{self.base_api}/issues?state=all&per_page=100")
        
        # Pull requests
        self.data['pulls'] = self._fetch_json(f"{self.base_api}/pulls?state=all&per_page=100")
        
        print(self.t['data_fetched'])
        return self.data
    
    def _fetch_json(self, url):
        """Fetch JSON data from GitHub API"""
        try:
            response = requests.get(url, timeout=10)
            if response.status_code == 200:
                return response.json()
            else:
                print(self.t['warning'].format(url=url, status=response.status_code))
                return []
        except Exception as e:
            print(self.t['error_fetch'].format(url=url, error=e))
            return []
    
    def analyze_basic_stats(self):
        """Analyze basic repository statistics"""
        basic = self.data.get('basic', {})
        return {
            'name': basic.get('name', 'Unknown'),
            'full_name': basic.get('full_name', f'{self.owner}/{self.repo}'),
            'description': basic.get('description', 'No description') or 'No description',
            'stars': basic.get('stargazers_count', 0),
            'forks': basic.get('forks_count', 0),
            'watchers': basic.get('watchers_count', 0),
            'open_issues': basic.get('open_issues_count', 0),
            'language': basic.get('language', self.t['unknown']),
            'created_at': basic.get('created_at', ''),
            'updated_at': basic.get('updated_at', ''),
            'size': basic.get('size', 0),
            'license': (basic.get('license') or {}).get('name', self.t['no_license']),
            'topics': basic.get('topics', []),
        }
    
    def analyze_contributors(self):
        """Analyze contributor activity"""
        contributors = self.data.get('contributors', [])
        if not contributors:
            return {'total': 0, 'top_contributors': [], 'avg_contributions': 0, 'total_contributions': 0}
        
        total_contributions = sum(c.get('contributions', 0) for c in contributors)
        top_contributors = [
            {
                'login': c.get('login', 'Unknown'),
                'contributions': c.get('contributions', 0)
            }
            for c in sorted(contributors, key=lambda x: x.get('contributions', 0), reverse=True)[:10]
        ]
        
        return {
            'total': len(contributors),
            'top_contributors': top_contributors,
            'avg_contributions': total_contributions / len(contributors),
            'total_contributions': total_contributions,
        }
    
    def analyze_commits(self):
        """Analyze commit activity"""
        commits = self.data.get('commits', [])
        commit_dates = []
        authors = set()
        
        for commit in commits:
            try:
                date_str = commit.get('commit', {}).get('author', {}).get('date', '')
                if date_str:
                    commit_dates.append(datetime.fromisoformat(date_str.replace('Z', '+00:00')))
                author = commit.get('author', {}).get('login', '') if commit.get('author') else None
                if author:
                    authors.add(author)
            except:
                continue
        
        return {
            'total_recent': len(commits),
            'commit_dates': commit_dates,
            'unique_authors': len(authors),
        }
    
    def analyze_issues(self):
        """Analyze issue statistics"""
        issues = self.data.get('issues', [])
        open_issues = [i for i in issues if i.get('state') == 'open' and 'pull_request' not in i]
        closed_issues = [i for i in issues if i.get('state') == 'closed' and 'pull_request' not in i]
        
        # Calculate average resolution time
        resolution_times = []
        for issue in closed_issues:
            created = issue.get('created_at')
            closed = issue.get('closed_at')
            if created and closed:
                try:
                    created_dt = datetime.fromisoformat(created.replace('Z', '+00:00'))
                    closed_dt = datetime.fromisoformat(closed.replace('Z', '+00:00'))
                    resolution_times.append((closed_dt - created_dt).days)
                except:
                    continue
        
        avg_resolution = sum(resolution_times) / len(resolution_times) if resolution_times else 0
        
        return {
            'total': len(open_issues) + len(closed_issues),
            'open': len(open_issues),
            'closed': len(closed_issues),
            'resolution_rate': len(closed_issues) / (len(open_issues) + len(closed_issues)) if (open_issues or closed_issues) else 0,
            'avg_resolution_time': avg_resolution,
        }
    
    def analyze_pull_requests(self):
        """Analyze pull request statistics"""
        pulls = self.data.get('pulls', [])
        
        open_prs = [p for p in pulls if p.get('state') == 'open']
        closed_prs = [p for p in pulls if p.get('state') == 'closed']
        merged_prs = [p for p in closed_prs if p.get('merged_at')]
        
        return {
            'total': len(pulls),
            'open': len(open_prs),
            'merged': len(merged_prs),
            'closed': len(closed_prs) - len(merged_prs),
            'merge_rate': len(merged_prs) / (len(merged_prs) + len(closed_prs) - len(merged_prs)) if closed_prs else 0,
        }
    
    def calculate_health_score(self):
        """Calculate overall repository health score"""
        basic = self.analyze_basic_stats()
        contributors = self.analyze_contributors()
        issues = self.analyze_issues()
        pulls = self.analyze_pull_requests()
        commits = self.analyze_commits()
        
        score = 0
        factors = []
        
        # Stars popularity (max 20 points)
        stars_score = min(20, basic['stars'] / 100)
        score += stars_score
        factors.append((self.t['stars_popularity'], stars_score, 20))
        
        # Contributor diversity (max 20 points)
        contrib_score = min(20, contributors['total'] * 2)
        score += contrib_score
        factors.append((self.t['contributor_diversity'], contrib_score, 20))
        
        # Issue resolution (max 20 points)
        issue_score = 20 * issues['resolution_rate'] if issues['total'] > 0 else 10
        score += issue_score
        factors.append((self.t['issue_resolution'], issue_score, 20))
        
        # PR merge rate (max 20 points)
        pr_score = 20 * pulls['merge_rate'] if pulls['total'] > 0 else 10
        score += pr_score
        factors.append((self.t['pr_merge_rate'], pr_score, 20))
        
        # Recent activity (max 20 points)
        activity_score = min(20, commits['total_recent'] / 5)
        score += activity_score
        factors.append((self.t['recent_activity_factor'], activity_score, 20))
        
        return {
            'total_score': round(score, 1),
            'grade': self._get_grade(score),
            'factors': factors,
        }
    
    def _get_grade(self, score):
        """Convert score to letter grade"""
        if score >= 90: return self.t['grade_A+']
        if score >= 80: return self.t['grade_A']
        if score >= 70: return self.t['grade_B+']
        if score >= 60: return self.t['grade_B']
        if score >= 50: return self.t['grade_C']
        if score >= 40: return self.t['grade_D']
        return self.t['grade_F']
    
    def generate_visualizations(self, output_dir='./output'):
        """Generate visualization charts"""
        os.makedirs(output_dir, exist_ok=True)
        
        # Create figure with subplots
        fig = plt.figure(figsize=(16, 10))
        fig.suptitle(f"{self.t['repo_health_report']}: {self.owner}/{self.repo}", fontsize=16, fontweight='bold')
        
        # 1. Basic Stats Pie Chart
        ax1 = plt.subplot(2, 3, 1)
        basic = self.analyze_basic_stats()
        stats_data = [basic['stars'], basic['forks'], basic['watchers']]
        colors = ['#FFD700', '#4169E1', '#32CD32']
        ax1.pie(stats_data, labels=[f"{self.t['stars']}\n{basic['stars']}", f"{self.t['forks']}\n{basic['forks']}", 
                                   f"{self.t['watchers']}\n{basic['watchers']}"], 
               colors=colors, autopct='%1.1f%%', startangle=90)
        ax1.set_title(self.t['repo_popularity'])
        
        # 2. Top Contributors Bar Chart
        ax2 = plt.subplot(2, 3, 2)
        contributors = self.analyze_contributors()
        if contributors['top_contributors']:
            logins = [c['login'][:10] for c in contributors['top_contributors'][:5]]
            contribs = [c['contributions'] for c in contributors['top_contributors'][:5]]
            ax2.barh(logins, contribs, color='#FF6B6B')
            ax2.set_xlabel(self.t['contributions'])
            ax2.set_title(self.t['top_contributors'])
            ax2.invert_yaxis()
        
        # 3. Health Score Gauge
        ax3 = plt.subplot(2, 3, 3)
        health = self.calculate_health_score()
        score = health['total_score']
        color = '#2ECC71' if score >= 70 else '#F39C12' if score >= 50 else '#E74C3C'
        ax3.barh([0], [score], color=color, height=0.5)
        ax3.set_xlim(0, 100)
        ax3.set_yticks([0])
        ax3.set_yticklabels([self.t['health_score']])
        ax3.set_xlabel(self.t['score'])
        ax3.set_title(f"{self.t['overall_health']}: {score}/100 - {health['grade']}")
        ax3.axvline(x=60, color='red', linestyle='--', alpha=0.5, label=self.t['pass_line'])
        
        # 4. Issue Status
        ax4 = plt.subplot(2, 3, 4)
        issues = self.analyze_issues()
        if issues['total'] > 0:
            issue_data = [issues['open'], issues['closed']]
            ax4.pie(issue_data, labels=[f"{self.t['open']}\n{issues['open']}", f"{self.t['closed']}\n{issues['closed']}"],
                   colors=['#E74C3C', '#2ECC71'], autopct='%1.1f%%')
            ax4.set_title(self.t['issue_status'].format(days=issues['avg_resolution_time']))
        
        # 5. PR Status
        ax5 = plt.subplot(2, 3, 5)
        pulls = self.analyze_pull_requests()
        if pulls['total'] > 0:
            pr_data = [pulls['open'], pulls['merged'], pulls['closed']]
            ax5.pie(pr_data, labels=[f"{self.t['open']}\n{pulls['open']}", f"{self.t['merged']}\n{pulls['merged']}", 
                                    f"{self.t['closed']}\n{pulls['closed']}"],
                   colors=['#F39C12', '#2ECC71', '#E74C3C'], autopct='%1.1f%%')
            ax5.set_title(self.t['pr_status'].format(rate=pulls['merge_rate']*100))
        
        # 6. Commit Activity Timeline
        ax6 = plt.subplot(2, 3, 6)
        commits = self.analyze_commits()
        if commits['commit_dates']:
            dates = commits['commit_dates']
            dates.sort()
            date_counts = Counter([d.date() for d in dates])
            x = list(date_counts.keys())
            y = list(date_counts.values())
            ax6.plot(x, y, color='#9B59B6', linewidth=2)
            ax6.fill_between(x, y, alpha=0.3, color='#9B59B6')
            ax6.set_xlabel(self.t['date'])
            ax6.set_ylabel(self.t['commits'])
            ax6.set_title(self.t['recent_activity'])
            ax6.tick_params(axis='x', rotation=45)
        
        plt.tight_layout()
        
        # Save figure
        chart_path = os.path.join(output_dir, f'{self.repo}_analysis.png')
        plt.savefig(chart_path, dpi=150, bbox_inches='tight')
        print(self.t['chart_saved'].format(path=chart_path))
        plt.close()
        
        return chart_path
    
    def generate_html_report(self, output_dir='./output'):
        """Generate HTML report"""
        os.makedirs(output_dir, exist_ok=True)
        
        basic = self.analyze_basic_stats()
        contributors = self.analyze_contributors()
        issues = self.analyze_issues()
        pulls = self.analyze_pull_requests()
        commits = self.analyze_commits()
        health = self.calculate_health_score()
        
        health_factors_html = ''.join([
            f'<tr><td>{name}</td><td>{score:.1f}/{max_score}</td><td>{"█" * int(score/max_score*20)}</td></tr>'
            for name, score, max_score in health['factors']
        ])
        
        contributors_html = ''.join([
            f'<li><strong>{c["login"]}</strong>: {c["contributions"]} {self.t["contributions"].lower()}</li>'
            for c in contributors['top_contributors'][:5]
        ])
        
        lang_attr = 'zh-CN' if self.lang == 'zh' else 'en'
        
        html = f'''<!DOCTYPE html>
<html lang="{lang_attr}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{self.t['repo_health_report']} - {self.owner}/{self.repo}</title>
    <style>
        body {{ font-family: 'Segoe UI', Arial, sans-serif; max-width: 1200px; margin: 0 auto; padding: 20px; background: #f5f5f5; }}
        .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; border-radius: 10px; margin-bottom: 20px; }}
        .header h1 {{ margin: 0; }}
        .score-card {{ background: white; padding: 20px; border-radius: 10px; margin-bottom: 20px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }}
        .score {{ font-size: 48px; font-weight: bold; color: {'#2ECC71' if health['total_score'] >= 70 else '#F39C12' if health['total_score'] >= 50 else '#E74C3C'}; }}
        .grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 20px; }}
        .card {{ background: white; padding: 20px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }}
        .card h3 {{ margin-top: 0; color: #333; }}
        table {{ width: 100%; border-collapse: collapse; }}
        th, td {{ padding: 10px; text-align: left; border-bottom: 1px solid #ddd; }}
        .chart {{ width: 100%; margin-top: 20px; border-radius: 10px; }}
        .footer {{ text-align: center; margin-top: 30px; color: #666; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>📊 {self.t['repo_health_report']}</h1>
        <p>{self.owner}/{self.repo}</p>
        <p>{basic['description']}</p>
    </div>
    
    <div class="score-card">
        <h2>{self.t['overall_health_score']}</h2>
        <div class="score">{health['total_score']}/100</div>
        <p style="font-size: 24px;">{self.t['grade']}: {health['grade']}</p>
        <table>
            <tr><th>{self.t['factor']}</th><th>{self.t['score']}</th><th>{self.t['bar']}</th></tr>
            {health_factors_html}
        </table>
    </div>
    
    <div class="grid">
        <div class="card">
            <h3>📈 {self.t['basic_statistics']}</h3>
            <p><strong>{self.t['stars']}:</strong> ⭐ {basic['stars']:,}</p>
            <p><strong>{self.t['forks']}:</strong> 🍴 {basic['forks']:,}</p>
            <p><strong>{self.t['watchers']}:</strong> 👁️ {basic['watchers']:,}</p>
            <p><strong>{self.t['primary_language']}:</strong> {basic['language']}</p>
            <p><strong>{self.t['license']}:</strong> {basic['license']}</p>
        </div>
        
        <div class="card">
            <h3>👥 {self.t['contributors']}</h3>
            <p><strong>{self.t['total_contributors']}:</strong> {contributors['total']}</p>
            <p><strong>{self.t['total_contributions']}:</strong> {contributors['total_contributions']:,}</p>
            <h4>{self.t['top_contributors_list']}:</h4>
            <ol>{contributors_html}</ol>
        </div>
        
        <div class="card">
            <h3>🐛 {self.t['issues']}</h3>
            <p><strong>{self.t['open_issues']}:</strong> {issues['open']}</p>
            <p><strong>{self.t['closed_issues']}:</strong> {issues['closed']}</p>
            <p><strong>{self.t['resolution_rate']}:</strong> {issues['resolution_rate']*100:.1f}%</p>
            <p><strong>{self.t['avg_resolution_time']}:</strong> {issues['avg_resolution_time']:.1f} {self.t['days']}</p>
        </div>
        
        <div class="card">
            <h3>🔀 {self.t['pull_requests']}</h3>
            <p><strong>{self.t['open_prs']}:</strong> {pulls['open']}</p>
            <p><strong>{self.t['merged_prs']}:</strong> {pulls['merged']}</p>
            <p><strong>{self.t['closed_prs']}:</strong> {pulls['closed']}</p>
            <p><strong>{self.t['merge_rate']}:</strong> {pulls['merge_rate']*100:.1f}%</p>
        </div>
        
        <div class="card">
            <h3>💻 {self.t['recent_commits']}</h3>
            <p><strong>{self.t['total_commits']}:</strong> {commits['total_recent']}</p>
            <p><strong>{self.t['unique_authors']}:</strong> {commits['unique_authors']}</p>
        </div>
        
        <div class="card">
            <h3>🎯 {self.t['health_factors']}</h3>
            <table>
                {health_factors_html}
            </table>
        </div>
    </div>
    
    <img src="{self.repo}_analysis.png" class="chart" alt="Analysis Chart">
    
    <div class="footer">
        <p>{self.t['report_footer']} | {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
    </div>
</body>
</html>'''
        
        html_path = os.path.join(output_dir, f'{self.repo}_report.html')
        with open(html_path, 'w', encoding='utf-8') as f:
            f.write(html)
        print(self.t['chart_saved'].format(path=html_path))
        return html_path
    
    def generate_summary(self):
        """Generate text summary of analysis"""
        basic = self.analyze_basic_stats()
        contributors = self.analyze_contributors()
        issues = self.analyze_issues()
        pulls = self.analyze_pull_requests()
        health = self.calculate_health_score()
        
        return f"""
{'=' * 60}
  {self.t['repo_health_report']}
{'=' * 60}

{self.t['repository']}: {basic['full_name']}
{self.t['description']}: {basic['description']}

{self.t['stars']}: {basic['stars']:,}
{self.t['forks']}: {basic['forks']:,}
{self.t['watchers']}: {basic['watchers']:,}

{self.t['health_score']}: {health['total_score']}/100 - {health['grade']}

{self.t['detailed_breakdown']}:
{chr(10).join([f"  • {name}: {score:.1f}/{max_score}" for name, score, max_score in health['factors']])}

{self.t['generated']}: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
"""


def main():
    """Main entry point"""
    import argparse
    
    parser = argparse.ArgumentParser(
        description='GitHub Repository Health Analyzer / GitHub仓库健康度分析器',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog='''
Examples:
  python analyzer.py https://github.com/torvalds/linux
  python analyzer.py https://github.com/torvalds/linux --lang zh
  python analyzer.py https://github.com/microsoft/vscode --output ./reports --lang zh
        '''
    )
    parser.add_argument('url', help='GitHub repository URL / GitHub 仓库地址')
    parser.add_argument('--output', '-o', default='./output', 
                       help='Output directory (default: ./output) / 输出目录 (默认: ./output)')
    parser.add_argument('--format', '-f', choices=['html', 'summary', 'json', 'all'], 
                       default='all', help='Output format / 输出格式')
    parser.add_argument('--lang', '-l', choices=['en', 'zh'], 
                       default='en', help='Language / 语言 (en: 英文, zh: 中文)')
    
    args = parser.parse_args()
    
    # Run analysis
    analyzer = GitHubRepoAnalyzer(args.url, lang=args.lang)
    analyzer.fetch_all_data()
    
    # Create output directory
    os.makedirs(args.output, exist_ok=True)
    
    # Generate outputs
    if args.format in ['all', 'summary']:
        print(analyzer.generate_summary())
    
    if args.format in ['all', 'json']:
        import json
        data = {
            'basic': analyzer.analyze_basic_stats(),
            'contributors': analyzer.analyze_contributors(),
            'issues': analyzer.analyze_issues(),
            'pulls': analyzer.analyze_pull_requests(),
            'health': analyzer.calculate_health_score(),
        }
        json_path = os.path.join(args.output, f'{analyzer.repo}_data.json')
        with open(json_path, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2, default=str, ensure_ascii=False)
        print(analyzer.t['json_saved'].format(path=json_path))
    
    if args.format in ['all', 'html']:
        analyzer.generate_visualizations(args.output)
        analyzer.generate_html_report(args.output)
    
    print(analyzer.t['analysis_complete'])


if __name__ == '__main__':
    # Fix Windows console encoding
    import sys
    import io
    if sys.platform == 'win32':
        sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='ignore')
        sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8', errors='ignore')
    main()
